spring:
  datasource:
    url: jdbc:mysql://120.77.174.154:3306/collaboration_blog
    username: root
    password: a123456!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: mail.yonyou.com
    username: yegk7
    password: yekun520
    default-encoding: utf-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
server:
  port: 8080
mybatis:
  mapperLocations: mapper/**.xml
  typeAliasesPackage: com.ytsssss.collaborationblog.domain
mail:
  fromMail:
     addr: yegk7@yonyou.com
