spring:
  datasource:
    url: 
    driver-class-name: 
    username: 
    password: 
  jpa:
    show-sql: true
  mail:
    host: 
    username: 
    password: 
    default-encoding: 
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
server:
  port: 8234
mybatis:
  mapperLocations: mapper/**.xml
  typeAliasesPackage: com.ytsssss.collaborationblog.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mail:
  fromMail:
     addr: 
qiniu:
  accessKey: 
  secretKey: 
  bucketName: 
  domainOfBucket: 
