spring:
  datasource:
    url: jdbc:
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: 
    username: 
    password: 
    default-encoding: utf-8
  redis:
    database: 0
    host: 
    port: 
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
server:
  port: 8234
mybatis:
  mapperLocations: mapper/**.xml
  typeAliasesPackage: com.ytsssss.collaborationblog.domain
mail:
  fromMail:
     addr: 
qiniu:
  accessKey: 
  secretKey: 
  bucketName: 
  domainOfBucket: 
