spring:
  datasource:
    url: jdbc:mysql://120.77.174.154:3306/collaboration_blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a123456!
  jpa:
    show-sql: true
  mail:
    host: mail.scu.edu.cn
    username: 2014141462313@stu.scu.edu.cn
    password: yekun520
    default-encoding: utf-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
server:
  port: 8234
mybatis:
  mapperLocations: mapper/**.xml
  typeAliasesPackage: com.ytsssss.collaborationblog.domain
mail:
  fromMail:
     addr: 2014141462313@stu.scu.edu.cn
qiniu:
  accessKey: jAyjcTkZaYdX7MZkoGg1oSll53r3nUQVXjkTYxXW
  secretKey: CzjtEg93N-zEjQCPsLL8seO---O1gXLDsd2Mc5IE
  bucketName: blog
  domainOfBucket: blog